<a href="https://colab.research.google.com/github/pedroHE000/Pr-tica---Agrupamento/blob/main/C%C3%B3pia_de_C%C3%B3pia_de_Atividade_Pr%C3%A1tica_Agrupamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução a prática do K-means


In [1]:
!pip install plotly --upgrade

In [2]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

# K-means

base idade salario


In [3]:
from sklearn.cluster import KMeans

In [4]:
x = [20 , 27, 21, 37, 46, 53, 55, 47, 52, 32, 39, 41, 39, 48, 48]
y = [1000, 1200, 2900, 1850, 900, 950, 2000, 2100, 3000, 5900, 4100, 5100, 7000, 5000, 6500]

In [5]:
grafico = px.scatter(x=x, y=y)
grafico.show()

In [6]:
base_salario = np.array([[20, 1000], [27,1200], [21,2900], [37,1850], [46,900], [53,950], [55,2000], [47,2100], [52,3000], [32,5900], [39,4100], [41,5100], [39,7000], [48,5000,], [48,6500]])

In [7]:
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [8]:
scaler_salario  = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [9]:
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [10]:
KMeans_salario = KMeans(n_clusters=3)
KMeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [11]:
centroides = KMeans_salario.cluster_centers_
centroides

array([[ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572],
       [-1.63312883, -0.77505093]])

In [12]:
scaler_salario.inverse_transform(KMeans_salario.cluster_centers_)

array([[  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ],
       [  22.66666667, 1700.        ]])

In [13]:
rotulos = KMeans_salario.labels_
rotulos

array([2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int32)

In [14]:
grafico1 = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color = rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:, 1], size = [12, 12, 12])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()